### YamlMime:ManagedReference
items:
- uid: Microsoft.Health.ApplicationProvisioning
  commentId: N:Microsoft.Health.ApplicationProvisioning
  id: Microsoft.Health.ApplicationProvisioning
  children:
  - Microsoft.Health.ApplicationProvisioning.Provisioner
  langs:
  - csharp
  - vb
  name: Microsoft.Health.ApplicationProvisioning
  nameWithType: Microsoft.Health.ApplicationProvisioning
  fullName: Microsoft.Health.ApplicationProvisioning
  type: Namespace
  assemblies:
  - Microsoft.Health
references:
- uid: Microsoft.Health.ApplicationProvisioning.Provisioner
  commentId: T:Microsoft.Health.ApplicationProvisioning.Provisioner
  isExternal: false
  name: Provisioner
  nameWithType: Provisioner
  fullName: Microsoft.Health.ApplicationProvisioning.Provisioner
