### YamlMime:ManagedReference
items:
- uid: Microsoft.Health.Utility.Configurations
  commentId: N:Microsoft.Health.Utility.Configurations
  id: Microsoft.Health.Utility.Configurations
  children:
  - Microsoft.Health.Utility.Configurations.ConfigurationDictionary
  - Microsoft.Health.Utility.Configurations.ConfigurationItem
  - Microsoft.Health.Utility.Configurations.ConfigurationManager
  - Microsoft.Health.Utility.Configurations.ConfigurationSet
  - Microsoft.Health.Utility.Configurations.DatabaseConnectionInfo
  - Microsoft.Health.Utility.Configurations.DatabaseConnectionInfoManager
  - Microsoft.Health.Utility.Configurations.DocumentationType
  - Microsoft.Health.Utility.Configurations.GlobalDatabaseConnectionStrings
  - Microsoft.Health.Utility.Configurations.GlobalUrls
  - Microsoft.Health.Utility.Configurations.HVComponentKeys
  - Microsoft.Health.Utility.Configurations.HVConfigGroupKeys
  - Microsoft.Health.Utility.Configurations.HVConfigurationAttribute
  - Microsoft.Health.Utility.Configurations.HVConfigurationClassAttribute
  - Microsoft.Health.Utility.Configurations.InvalidConfigurationException
  - Microsoft.Health.Utility.Configurations.QueryPath
  - Microsoft.Health.Utility.Configurations.QueryPathSet
  - Microsoft.Health.Utility.Configurations.SetConfigResult
  - Microsoft.Health.Utility.Configurations.XmlSerializableCollection`1
  - Microsoft.Health.Utility.Configurations.XmlSerializableDictionary`2
  langs:
  - csharp
  - vb
  name: Microsoft.Health.Utility.Configurations
  nameWithType: Microsoft.Health.Utility.Configurations
  fullName: Microsoft.Health.Utility.Configurations
  type: Namespace
  assemblies:
  - Microsoft.Health.Utility
references:
- uid: Microsoft.Health.Utility.Configurations.ConfigurationDictionary
  commentId: T:Microsoft.Health.Utility.Configurations.ConfigurationDictionary
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: ConfigurationDictionary
  nameWithType: ConfigurationDictionary
  fullName: Microsoft.Health.Utility.Configurations.ConfigurationDictionary
- uid: Microsoft.Health.Utility.Configurations.ConfigurationItem
  commentId: T:Microsoft.Health.Utility.Configurations.ConfigurationItem
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: ConfigurationItem
  nameWithType: ConfigurationItem
  fullName: Microsoft.Health.Utility.Configurations.ConfigurationItem
- uid: Microsoft.Health.Utility.Configurations.ConfigurationManager
  commentId: T:Microsoft.Health.Utility.Configurations.ConfigurationManager
  isExternal: false
  name: ConfigurationManager
  nameWithType: ConfigurationManager
  fullName: Microsoft.Health.Utility.Configurations.ConfigurationManager
- uid: Microsoft.Health.Utility.Configurations.ConfigurationSet
  commentId: T:Microsoft.Health.Utility.Configurations.ConfigurationSet
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: ConfigurationSet
  nameWithType: ConfigurationSet
  fullName: Microsoft.Health.Utility.Configurations.ConfigurationSet
- uid: Microsoft.Health.Utility.Configurations.GlobalDatabaseConnectionStrings
  commentId: T:Microsoft.Health.Utility.Configurations.GlobalDatabaseConnectionStrings
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: GlobalDatabaseConnectionStrings
  nameWithType: GlobalDatabaseConnectionStrings
  fullName: Microsoft.Health.Utility.Configurations.GlobalDatabaseConnectionStrings
- uid: Microsoft.Health.Utility.Configurations.GlobalUrls
  commentId: T:Microsoft.Health.Utility.Configurations.GlobalUrls
  isExternal: false
  name: GlobalUrls
  nameWithType: GlobalUrls
  fullName: Microsoft.Health.Utility.Configurations.GlobalUrls
- uid: Microsoft.Health.Utility.Configurations.HVComponentKeys
  commentId: T:Microsoft.Health.Utility.Configurations.HVComponentKeys
  isExternal: false
  name: HVComponentKeys
  nameWithType: HVComponentKeys
  fullName: Microsoft.Health.Utility.Configurations.HVComponentKeys
- uid: Microsoft.Health.Utility.Configurations.HVConfigGroupKeys
  commentId: T:Microsoft.Health.Utility.Configurations.HVConfigGroupKeys
  isExternal: false
  name: HVConfigGroupKeys
  nameWithType: HVConfigGroupKeys
  fullName: Microsoft.Health.Utility.Configurations.HVConfigGroupKeys
- uid: Microsoft.Health.Utility.Configurations.DocumentationType
  commentId: T:Microsoft.Health.Utility.Configurations.DocumentationType
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: DocumentationType
  nameWithType: DocumentationType
  fullName: Microsoft.Health.Utility.Configurations.DocumentationType
- uid: Microsoft.Health.Utility.Configurations.HVConfigurationAttribute
  commentId: T:Microsoft.Health.Utility.Configurations.HVConfigurationAttribute
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: HVConfigurationAttribute
  nameWithType: HVConfigurationAttribute
  fullName: Microsoft.Health.Utility.Configurations.HVConfigurationAttribute
- uid: Microsoft.Health.Utility.Configurations.HVConfigurationClassAttribute
  commentId: T:Microsoft.Health.Utility.Configurations.HVConfigurationClassAttribute
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: HVConfigurationClassAttribute
  nameWithType: HVConfigurationClassAttribute
  fullName: Microsoft.Health.Utility.Configurations.HVConfigurationClassAttribute
- uid: Microsoft.Health.Utility.Configurations.InvalidConfigurationException
  commentId: T:Microsoft.Health.Utility.Configurations.InvalidConfigurationException
  isExternal: false
  name: InvalidConfigurationException
  nameWithType: InvalidConfigurationException
  fullName: Microsoft.Health.Utility.Configurations.InvalidConfigurationException
- uid: Microsoft.Health.Utility.Configurations.QueryPath
  commentId: T:Microsoft.Health.Utility.Configurations.QueryPath
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: QueryPath
  nameWithType: QueryPath
  fullName: Microsoft.Health.Utility.Configurations.QueryPath
- uid: Microsoft.Health.Utility.Configurations.QueryPathSet
  commentId: T:Microsoft.Health.Utility.Configurations.QueryPathSet
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: QueryPathSet
  nameWithType: QueryPathSet
  fullName: Microsoft.Health.Utility.Configurations.QueryPathSet
- uid: Microsoft.Health.Utility.Configurations.SetConfigResult
  commentId: T:Microsoft.Health.Utility.Configurations.SetConfigResult
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: SetConfigResult
  nameWithType: SetConfigResult
  fullName: Microsoft.Health.Utility.Configurations.SetConfigResult
- uid: Microsoft.Health.Utility.Configurations.XmlSerializableCollection`1
  commentId: T:Microsoft.Health.Utility.Configurations.XmlSerializableCollection`1
  isExternal: false
  name: XmlSerializableCollection<T>
  nameWithType: XmlSerializableCollection<T>
  fullName: Microsoft.Health.Utility.Configurations.XmlSerializableCollection<T>
  nameWithType.vb: XmlSerializableCollection(Of T)
  fullName.vb: Microsoft.Health.Utility.Configurations.XmlSerializableCollection(Of T)
  name.vb: XmlSerializableCollection(Of T)
  spec.csharp:
  - uid: Microsoft.Health.Utility.Configurations.XmlSerializableCollection`1
    name: XmlSerializableCollection
    nameWithType: XmlSerializableCollection
    fullName: Microsoft.Health.Utility.Configurations.XmlSerializableCollection
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Health.Utility.Configurations.XmlSerializableCollection`1
    name: XmlSerializableCollection
    nameWithType: XmlSerializableCollection
    fullName: Microsoft.Health.Utility.Configurations.XmlSerializableCollection
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Health.Utility.Configurations.XmlSerializableDictionary`2
  commentId: T:Microsoft.Health.Utility.Configurations.XmlSerializableDictionary`2
  isExternal: false
  name: XmlSerializableDictionary<TKey, TValue>
  nameWithType: XmlSerializableDictionary<TKey, TValue>
  fullName: Microsoft.Health.Utility.Configurations.XmlSerializableDictionary<TKey, TValue>
  nameWithType.vb: XmlSerializableDictionary(Of TKey, TValue)
  fullName.vb: Microsoft.Health.Utility.Configurations.XmlSerializableDictionary(Of TKey, TValue)
  name.vb: XmlSerializableDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: Microsoft.Health.Utility.Configurations.XmlSerializableDictionary`2
    name: XmlSerializableDictionary
    nameWithType: XmlSerializableDictionary
    fullName: Microsoft.Health.Utility.Configurations.XmlSerializableDictionary
  - name: <
    nameWithType: <
    fullName: <
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Microsoft.Health.Utility.Configurations.XmlSerializableDictionary`2
    name: XmlSerializableDictionary
    nameWithType: XmlSerializableDictionary
    fullName: Microsoft.Health.Utility.Configurations.XmlSerializableDictionary
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Health.Utility.Configurations.DatabaseConnectionInfoManager
  commentId: T:Microsoft.Health.Utility.Configurations.DatabaseConnectionInfoManager
  isExternal: false
  name: DatabaseConnectionInfoManager
  nameWithType: DatabaseConnectionInfoManager
  fullName: Microsoft.Health.Utility.Configurations.DatabaseConnectionInfoManager
- uid: Microsoft.Health.Utility.Configurations.DatabaseConnectionInfo
  commentId: T:Microsoft.Health.Utility.Configurations.DatabaseConnectionInfo
  parent: Microsoft.Health.Utility.Configurations
  isExternal: false
  name: DatabaseConnectionInfo
  nameWithType: DatabaseConnectionInfo
  fullName: Microsoft.Health.Utility.Configurations.DatabaseConnectionInfo
- uid: Microsoft.Health.Utility.Configurations
  commentId: N:Microsoft.Health.Utility.Configurations
  isExternal: false
  name: Microsoft.Health.Utility.Configurations
  nameWithType: Microsoft.Health.Utility.Configurations
  fullName: Microsoft.Health.Utility.Configurations
