### YamlMime:ManagedReference
items:
- uid: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  commentId: T:Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  id: ApplicationRecordAuthorizationAction
  parent: Microsoft.Health.Authentication
  children:
  - Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.AuthorizationRequired
  - Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.NoActionRequired
  - Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.ReauthorizationNotPossible
  - Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.ReauthorizationRequired
  - Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.RecordLocationNotSupported
  - Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.Unknown
  langs:
  - csharp
  - vb
  name: ApplicationRecordAuthorizationAction
  nameWithType: ApplicationRecordAuthorizationAction
  fullName: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  type: Enum
  source:
    remote:
      path: Microsoft.Health/Authentication/ApplicationRecordAuthorizationAction.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: ApplicationRecordAuthorizationAction
    path: Authentication/ApplicationRecordAuthorizationAction.cs
    startLine: 12
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health.Authentication
  summary: "\nEnumeration of the application record authorization action codes.\n"
  example: []
  syntax:
    content: public enum ApplicationRecordAuthorizationAction
    content.vb: Public Enum ApplicationRecordAuthorizationAction
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.Unknown
  commentId: F:Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.Unknown
  id: Unknown
  parent: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: ApplicationRecordAuthorizationAction.Unknown
  fullName: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.Unknown
  type: Field
  source:
    remote:
      path: Microsoft.Health/Authentication/ApplicationRecordAuthorizationAction.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: Unknown
    path: Authentication/ApplicationRecordAuthorizationAction.cs
    startLine: 18
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health.Authentication
  summary: "\nThe server returned a value that is not understood by this client.\n"
  example: []
  syntax:
    content: Unknown = 0
    return:
      type: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.AuthorizationRequired
  commentId: F:Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.AuthorizationRequired
  id: AuthorizationRequired
  parent: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  langs:
  - csharp
  - vb
  name: AuthorizationRequired
  nameWithType: ApplicationRecordAuthorizationAction.AuthorizationRequired
  fullName: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.AuthorizationRequired
  type: Field
  source:
    remote:
      path: Microsoft.Health/Authentication/ApplicationRecordAuthorizationAction.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: AuthorizationRequired
    path: Authentication/ApplicationRecordAuthorizationAction.cs
    startLine: 24
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health.Authentication
  summary: "\nThe application has never been authorized.\n"
  example: []
  syntax:
    content: AuthorizationRequired = 1
    return:
      type: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.ReauthorizationRequired
  commentId: F:Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.ReauthorizationRequired
  id: ReauthorizationRequired
  parent: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  langs:
  - csharp
  - vb
  name: ReauthorizationRequired
  nameWithType: ApplicationRecordAuthorizationAction.ReauthorizationRequired
  fullName: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.ReauthorizationRequired
  type: Field
  source:
    remote:
      path: Microsoft.Health/Authentication/ApplicationRecordAuthorizationAction.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: ReauthorizationRequired
    path: Authentication/ApplicationRecordAuthorizationAction.cs
    startLine: 30
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health.Authentication
  summary: "\nThe application both requires and can do re-authorization.\n"
  example: []
  syntax:
    content: ReauthorizationRequired = 2
    return:
      type: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.ReauthorizationNotPossible
  commentId: F:Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.ReauthorizationNotPossible
  id: ReauthorizationNotPossible
  parent: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  langs:
  - csharp
  - vb
  name: ReauthorizationNotPossible
  nameWithType: ApplicationRecordAuthorizationAction.ReauthorizationNotPossible
  fullName: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.ReauthorizationNotPossible
  type: Field
  source:
    remote:
      path: Microsoft.Health/Authentication/ApplicationRecordAuthorizationAction.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: ReauthorizationNotPossible
    path: Authentication/ApplicationRecordAuthorizationAction.cs
    startLine: 36
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health.Authentication
  summary: "\nThe application requires but cannot do re-authorization.\n"
  example: []
  syntax:
    content: ReauthorizationNotPossible = 3
    return:
      type: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.NoActionRequired
  commentId: F:Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.NoActionRequired
  id: NoActionRequired
  parent: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  langs:
  - csharp
  - vb
  name: NoActionRequired
  nameWithType: ApplicationRecordAuthorizationAction.NoActionRequired
  fullName: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.NoActionRequired
  type: Field
  source:
    remote:
      path: Microsoft.Health/Authentication/ApplicationRecordAuthorizationAction.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: NoActionRequired
    path: Authentication/ApplicationRecordAuthorizationAction.cs
    startLine: 42
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health.Authentication
  summary: "\nThere are no actions required.\n"
  example: []
  syntax:
    content: NoActionRequired = 4
    return:
      type: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.RecordLocationNotSupported
  commentId: F:Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.RecordLocationNotSupported
  id: RecordLocationNotSupported
  parent: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  langs:
  - csharp
  - vb
  name: RecordLocationNotSupported
  nameWithType: ApplicationRecordAuthorizationAction.RecordLocationNotSupported
  fullName: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction.RecordLocationNotSupported
  type: Field
  source:
    remote:
      path: Microsoft.Health/Authentication/ApplicationRecordAuthorizationAction.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: RecordLocationNotSupported
    path: Authentication/ApplicationRecordAuthorizationAction.cs
    startLine: 47
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health.Authentication
  summary: "\nThe record location isn't supported by the application.\n"
  example: []
  syntax:
    content: RecordLocationNotSupported = 5
    return:
      type: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Health.Authentication
  commentId: N:Microsoft.Health.Authentication
  isExternal: false
  name: Microsoft.Health.Authentication
  nameWithType: Microsoft.Health.Authentication
  fullName: Microsoft.Health.Authentication
- uid: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  commentId: T:Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
  parent: Microsoft.Health.Authentication
  isExternal: false
  name: ApplicationRecordAuthorizationAction
  nameWithType: ApplicationRecordAuthorizationAction
  fullName: Microsoft.Health.Authentication.ApplicationRecordAuthorizationAction
