### YamlMime:ManagedReference
items:
- uid: Microsoft.Health.ApplicationOptions
  commentId: T:Microsoft.Health.ApplicationOptions
  id: ApplicationOptions
  parent: Microsoft.Health
  children:
  - Microsoft.Health.ApplicationOptions.All
  - Microsoft.Health.ApplicationOptions.ApplicationAuthorizationRequired
  - Microsoft.Health.ApplicationOptions.Default
  - Microsoft.Health.ApplicationOptions.None
  - Microsoft.Health.ApplicationOptions.PersistentTokensAllowed
  - Microsoft.Health.ApplicationOptions.PublishApplication
  - Microsoft.Health.ApplicationOptions.RestrictApplicationUsers
  langs:
  - csharp
  - vb
  name: ApplicationOptions
  nameWithType: ApplicationOptions
  fullName: Microsoft.Health.ApplicationOptions
  type: Enum
  source:
    remote:
      path: Microsoft.Health/ApplicationOptions.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: ApplicationOptions
    path: ApplicationOptions.cs
    startLine: 17
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health
  summary: "\nOptional configuration settings for HealthVault applications.\n"
  remarks: "\nThe default value is None.\n"
  example: []
  syntax:
    content: >-
      [Flags]

      public enum ApplicationOptions
    content.vb: >-
      <Flags>

      Public Enum ApplicationOptions
  attributes:
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Microsoft.Health.ApplicationOptions.None
  commentId: F:Microsoft.Health.ApplicationOptions.None
  id: None
  parent: Microsoft.Health.ApplicationOptions
  langs:
  - csharp
  - vb
  name: None
  nameWithType: ApplicationOptions.None
  fullName: Microsoft.Health.ApplicationOptions.None
  type: Field
  source:
    remote:
      path: Microsoft.Health/ApplicationOptions.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: None
    path: ApplicationOptions.cs
    startLine: 24
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health
  summary: "\nNo optional application settings specified.\n"
  example: []
  syntax:
    content: None = 0
    return:
      type: Microsoft.Health.ApplicationOptions
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.ApplicationOptions.PersistentTokensAllowed
  commentId: F:Microsoft.Health.ApplicationOptions.PersistentTokensAllowed
  id: PersistentTokensAllowed
  parent: Microsoft.Health.ApplicationOptions
  langs:
  - csharp
  - vb
  name: PersistentTokensAllowed
  nameWithType: ApplicationOptions.PersistentTokensAllowed
  fullName: Microsoft.Health.ApplicationOptions.PersistentTokensAllowed
  type: Field
  source:
    remote:
      path: Microsoft.Health/ApplicationOptions.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: PersistentTokensAllowed
    path: ApplicationOptions.cs
    startLine: 36
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health
  summary: "\nThe application allows the user to stay logged in to the application across browser\nsession.\n"
  remarks: "\nThis setting enables the \"Keep me signed in on this computer\" checkbox on the\nHealthVault login page.\n"
  example: []
  syntax:
    content: PersistentTokensAllowed = 1
    return:
      type: Microsoft.Health.ApplicationOptions
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.ApplicationOptions.ApplicationAuthorizationRequired
  commentId: F:Microsoft.Health.ApplicationOptions.ApplicationAuthorizationRequired
  id: ApplicationAuthorizationRequired
  parent: Microsoft.Health.ApplicationOptions
  langs:
  - csharp
  - vb
  name: ApplicationAuthorizationRequired
  nameWithType: ApplicationOptions.ApplicationAuthorizationRequired
  fullName: Microsoft.Health.ApplicationOptions.ApplicationAuthorizationRequired
  type: Field
  source:
    remote:
      path: Microsoft.Health/ApplicationOptions.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: ApplicationAuthorizationRequired
    path: ApplicationOptions.cs
    startLine: 43
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health
  summary: "\nThe application is required to notify HealthVault that a user has been authorized to\nuse the application.\nThis property will be soon removed. Please use RestrictApplicationUsers instead\n"
  example: []
  syntax:
    content: ApplicationAuthorizationRequired = 2
    return:
      type: Microsoft.Health.ApplicationOptions
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.ApplicationOptions.RestrictApplicationUsers
  commentId: F:Microsoft.Health.ApplicationOptions.RestrictApplicationUsers
  id: RestrictApplicationUsers
  parent: Microsoft.Health.ApplicationOptions
  langs:
  - csharp
  - vb
  name: RestrictApplicationUsers
  nameWithType: ApplicationOptions.RestrictApplicationUsers
  fullName: Microsoft.Health.ApplicationOptions.RestrictApplicationUsers
  type: Field
  source:
    remote:
      path: Microsoft.Health/ApplicationOptions.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: RestrictApplicationUsers
    path: ApplicationOptions.cs
    startLine: 57
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health
  summary: "\nThe application is required to notify HealthVault that a user has been authorized to\nuse the application.\n"
  remarks: "\nIf this option is specified, the application must authorize HealthVault to allow the\nuser to use the application. For example, if the application requires a subscription \nfor use it could enable this option and then notify HealthVault when the status of the\nsubscription has changed. In this case HealthVault will prevent the user from logging\nin to the application if the subscription has lapsed.\n"
  example: []
  syntax:
    content: RestrictApplicationUsers = 8
    return:
      type: Microsoft.Health.ApplicationOptions
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.ApplicationOptions.PublishApplication
  commentId: F:Microsoft.Health.ApplicationOptions.PublishApplication
  id: PublishApplication
  parent: Microsoft.Health.ApplicationOptions
  langs:
  - csharp
  - vb
  name: PublishApplication
  nameWithType: ApplicationOptions.PublishApplication
  fullName: Microsoft.Health.ApplicationOptions.PublishApplication
  type: Field
  source:
    remote:
      path: Microsoft.Health/ApplicationOptions.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: PublishApplication
    path: ApplicationOptions.cs
    startLine: 63
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health
  summary: "\nThe application will be published to the application directory for users to find.\n"
  example: []
  syntax:
    content: PublishApplication = 4
    return:
      type: Microsoft.Health.ApplicationOptions
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.ApplicationOptions.All
  commentId: F:Microsoft.Health.ApplicationOptions.All
  id: All
  parent: Microsoft.Health.ApplicationOptions
  langs:
  - csharp
  - vb
  name: All
  nameWithType: ApplicationOptions.All
  fullName: Microsoft.Health.ApplicationOptions.All
  type: Field
  source:
    remote:
      path: Microsoft.Health/ApplicationOptions.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: All
    path: ApplicationOptions.cs
    startLine: 69
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health
  summary: "\nAll application options are specified.\n"
  example: []
  syntax:
    content: All = 7
    return:
      type: Microsoft.Health.ApplicationOptions
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Microsoft.Health.ApplicationOptions.Default
  commentId: F:Microsoft.Health.ApplicationOptions.Default
  id: Default
  parent: Microsoft.Health.ApplicationOptions
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: ApplicationOptions.Default
  fullName: Microsoft.Health.ApplicationOptions.Default
  type: Field
  source:
    remote:
      path: Microsoft.Health/ApplicationOptions.cs
      branch: personal/justhu/docfx
      repo: https://microsofthealth.visualstudio.com/DefaultCollection/Health/_git/healthvault-sdk
    id: Default
    path: ApplicationOptions.cs
    startLine: 75
  assemblies:
  - Microsoft.Health
  namespace: Microsoft.Health
  summary: "\nThe default is no options specified.\n"
  example: []
  syntax:
    content: Default = 0
    return:
      type: Microsoft.Health.ApplicationOptions
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Microsoft.Health
  commentId: N:Microsoft.Health
  isExternal: false
  name: Microsoft.Health
  nameWithType: Microsoft.Health
  fullName: Microsoft.Health
- uid: Microsoft.Health.ApplicationOptions
  commentId: T:Microsoft.Health.ApplicationOptions
  parent: Microsoft.Health
  isExternal: false
  name: ApplicationOptions
  nameWithType: ApplicationOptions
  fullName: Microsoft.Health.ApplicationOptions
