items:
- uid: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request
  id: request
  children:
  - com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatiodba06241ce97b0bddf5696f7b2f2a02a
  href: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request.yml
  langs:
  - java
  name: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request
  fullName: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request
  type: Namespace
  source:
    remote:
      path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/methods/removeapplicationauthorization/request/RemoveApplicationAuthorizationRequest.java
      branch: master
      repo: https://github.com/microsoft/healthvault-java-sdk
    path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/methods/removeapplicationauthorization/request/RemoveApplicationAuthorizationRequest.java
  syntax:
    content: package com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request
references:
- uid: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatiodba06241ce97b0bddf5696f7b2f2a02a
  parent: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request
  href: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatiodba06241ce97b0bddf5696f7b2f2a02a.yml
  name: RemoveApplicationAuthorizationRequest
  fullName: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request.RemoveApplicationAuthorizationRequest
  type: Class
  syntax:
    content: public class RemoveApplicationAuthorizationRequest implements HVRequestInfo
