items:
- uid: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatio270fea95a27da86269b05143c4114f92
  id: removeapplicationauthorizatio270fea95a27da86269b05143c4114f92
  parent: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response
  href: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatio270fea95a27da86269b05143c4114f92.yml
  langs:
  - java
  name: RemoveApplicationAuthorizationResponse
  fullName: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response.RemoveApplicationAuthorizationResponse
  type: Class
  source:
    remote:
      path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/methods/removeapplicationauthorization/response/RemoveApplicationAuthorizationResponse.java
      branch: master
      repo: https://github.com/microsoft/healthvault-java-sdk
    path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/methods/removeapplicationauthorization/response/RemoveApplicationAuthorizationResponse.java
    startLine: 4
  package: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response
  syntax:
    content: public class RemoveApplicationAuthorizationResponse extends Response
  inheritance:
  - java.lang.Object
  - com.microsoft.hsg.android.simplexml.methods.response._response
  inheritedMembers:
  - com.microsoft.hsg.android.simplexml.methods.response._response.getStatus()
  - com.microsoft.hsg.android.simplexml.methods.response._response.hasError()
  - com.microsoft.hsg.android.simplexml.methods.response._response.isSuccess()
  - com.microsoft.hsg.android.simplexml.methods.response._response.setStatus(ResponseStatus)
  - com.microsoft.hsg.android.simplexml.methods.response._response.status()
references:
- uid: com.microsoft.hsg.android.simplexml.methods.response._response.getStatus()
  parent: com.microsoft.hsg.android.simplexml.methods.response._response
  href: com.microsoft.hsg.android.simplexml.methods.response._response.yml
  name: getStatus()
  fullName: ResponseStatus com.microsoft.hsg.android.simplexml.methods.response.Response.getStatus()
  type: Method
  syntax:
    content: public ResponseStatus getStatus()
    return:
      type: com.microsoft.hsg.android.simplexml.methods.response._response_status
- uid: com.microsoft.hsg.android.simplexml.methods.response._response.hasError()
  parent: com.microsoft.hsg.android.simplexml.methods.response._response
  href: com.microsoft.hsg.android.simplexml.methods.response._response.yml
  name: hasError()
  fullName: Boolean com.microsoft.hsg.android.simplexml.methods.response.Response.hasError()
  type: Method
  syntax:
    content: public Boolean hasError()
    return:
      type: 866c2227
- uid: com.microsoft.hsg.android.simplexml.methods.response._response.isSuccess()
  parent: com.microsoft.hsg.android.simplexml.methods.response._response
  href: com.microsoft.hsg.android.simplexml.methods.response._response.yml
  name: isSuccess()
  fullName: Boolean com.microsoft.hsg.android.simplexml.methods.response.Response.isSuccess()
  type: Method
  syntax:
    content: public Boolean isSuccess()
    return:
      type: 866c2227
- uid: com.microsoft.hsg.android.simplexml.methods.response._response.setStatus(ResponseStatus)
  parent: com.microsoft.hsg.android.simplexml.methods.response._response
  href: com.microsoft.hsg.android.simplexml.methods.response._response.yml
  name: setStatus(ResponseStatus status)
  fullName: void com.microsoft.hsg.android.simplexml.methods.response.Response.setStatus(ResponseStatus status)
  type: Method
  syntax:
    content: public void setStatus(ResponseStatus status)
    parameters:
    - id: status
      type: com.microsoft.hsg.android.simplexml.methods.response._response_status
- uid: com.microsoft.hsg.android.simplexml.methods.response._response.status()
  parent: com.microsoft.hsg.android.simplexml.methods.response._response
  href: com.microsoft.hsg.android.simplexml.methods.response._response.yml
  name: status
  fullName: ResponseStatus com.microsoft.hsg.android.simplexml.methods.response.Response.status
  type: Field
  syntax:
    content: protected ResponseStatus status
    return:
      type: com.microsoft.hsg.android.simplexml.methods.response._response_status
- uid: com.microsoft.hsg.android.simplexml.methods.response._response
  parent: com.microsoft.hsg.android.simplexml.methods.response
  href: com.microsoft.hsg.android.simplexml.methods.response._response.yml
  name: Response
  fullName: com.microsoft.hsg.android.simplexml.methods.response.Response
  type: Class
  syntax:
    content: public class Response
