items:
- uid: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response
  id: response
  children:
  - com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatio270fea95a27da86269b05143c4114f92
  href: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response.yml
  langs:
  - java
  name: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response
  fullName: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response
  type: Namespace
  source:
    remote:
      path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/methods/removeapplicationauthorization/response/RemoveApplicationAuthorizationResponse.java
      branch: master
      repo: https://github.com/microsoft/healthvault-java-sdk
    path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/methods/removeapplicationauthorization/response/RemoveApplicationAuthorizationResponse.java
  syntax:
    content: package com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response
references:
- uid: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatio270fea95a27da86269b05143c4114f92
  parent: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response
  href: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatio270fea95a27da86269b05143c4114f92.yml
  name: RemoveApplicationAuthorizationResponse
  fullName: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.response.RemoveApplicationAuthorizationResponse
  type: Class
  syntax:
    content: public class RemoveApplicationAuthorizationResponse extends Response
