items:
- uid: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatiodba06241ce97b0bddf5696f7b2f2a02a
  id: removeapplicationauthorizatiodba06241ce97b0bddf5696f7b2f2a02a
  parent: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request
  href: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorizatiodba06241ce97b0bddf5696f7b2f2a02a.yml
  langs:
  - java
  name: RemoveApplicationAuthorizationRequest
  fullName: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request.RemoveApplicationAuthorizationRequest
  type: Class
  source:
    remote:
      path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/methods/removeapplicationauthorization/request/RemoveApplicationAuthorizationRequest.java
      branch: master
      repo: https://github.com/microsoft/healthvault-java-sdk
    path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/methods/removeapplicationauthorization/request/RemoveApplicationAuthorizationRequest.java
    startLine: 9
  package: com.microsoft.hsg.android.simplexml.methods.removeapplicationauthorization.request
  syntax:
    content: public class RemoveApplicationAuthorizationRequest implements HVRequestInfo
  inheritance:
  - java.lang.Object
  - com.microsoft.hsg.android.simplexml.methods.request._h_v_request_info
references:
- uid: com.microsoft.hsg.android.simplexml.methods.request._h_v_request_info
  parent: com.microsoft.hsg.android.simplexml.methods.request
  href: com.microsoft.hsg.android.simplexml.methods.request._h_v_request_info.yml
  name: HVRequestInfo
  fullName: com.microsoft.hsg.android.simplexml.methods.request.HVRequestInfo
  type: Interface
  syntax:
    content: public interface HVRequestInfo
