items:
- uid: com.microsoft.hsg.android.simplexml._configure_log4_j
  id: _configure_log4_j
  parent: com.microsoft.hsg.android.simplexml
  children:
  - com.microsoft.hsg.android.simplexml._configure_log4_j.configure()
  href: com.microsoft.hsg.android.simplexml._configure_log4_j.yml
  langs:
  - java
  name: ConfigureLog4J
  fullName: com.microsoft.hsg.android.simplexml.ConfigureLog4J
  type: Class
  source:
    remote: &o0
      path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/ConfigureLog4J.java
      branch: master
      repo: https://github.com/microsoft/healthvault-java-sdk
    path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/ConfigureLog4J.java
    startLine: 6
  package: com.microsoft.hsg.android.simplexml
  syntax:
    content: public class ConfigureLog4J
  inheritance:
  - java.lang.Object
- uid: com.microsoft.hsg.android.simplexml._configure_log4_j.configure()
  id: configure()
  parent: com.microsoft.hsg.android.simplexml._configure_log4_j
  href: com.microsoft.hsg.android.simplexml._configure_log4_j.yml
  langs:
  - java
  name: configure()
  fullName: static void com.microsoft.hsg.android.simplexml.ConfigureLog4J.configure()
  type: Method
  source:
    remote: *o0
    path: android-sdk-simplexml/src/main/java/com/microsoft/hsg/android/simplexml/ConfigureLog4J.java
    startLine: 7
  package: com.microsoft.hsg.android.simplexml
  syntax:
    content: public static void configure()
references: []
